---
- hosts: all
  gather_facts: no
  become: yes
  vars:
    azure_conf_dir: /etc/origin/cloudprovider
    azure_var: "{{ azure_conf_dir }}/azurevars.yaml"

  tasks:
  - name: make sure {{ azure_conf_dir }} exists
    file:
      state: directory
      path: "{{ azure_conf_dir }}"

  - name: populate {{ azure_var }}
    copy:
      dest: "{{ azure_var }}"
      content: | 
        aadClientId: "{{ lookup('env','AADCLIENTID') }}"
        aadClientSecret: "{{ lookup('env','AADCLIENTSECRET') }}"
        subscriptionId: "{{ lookup('env','SUBSCRIPTIONID') }}"
        tenantId: "{{ lookup('env','TENANTID') }}"

