---
- hosts: master0
  gather_facts: no
  remote_user: "{{ lookup('env','SUDOUSER') }}"
  become: yes
  become_method: sudo
  vars:
    description: "Set registry to use Azure Storage"
  tasks:
  - name: Configure docker-registry to use Azure Storage
    shell: oc set env dc docker-registry -e REGISTRY_STORAGE=azure -e REGISTRY_STORAGE_AZURE_ACCOUNTNAME={{ lookup('env','REGISTRYSA') }} -e REGISTRY_STORAGE_AZURE_ACCOUNTKEY={{ lookup('env','ACCOUNTKEY') }} -e REGISTRY_STORAGE_AZURE_CONTAINER=registry -e REGISTRY_STORAGE_AZURE_REALM=core.usgovcloudapi.net
