---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
  - lineinfile:
      dest: /etc/ansible/ansible.cfg
      regexp: '^library '
      insertafter: '#library        = /usr/share/my_modules/'
      line: 'library = /home/{{ lookup('env','SUDOUSER') }}/openshift-ansible/roles/lib_utils/library/'
