---
- name: Get contrail nodes and ips
  include_role:
    name: contrail_common

#- name: Generate and copy etcd client certs to contrail nodes
#  include_tasks: etcd_certs.yaml
#  when:
#    - inventory_hostname in contrail_masters
#    - inventory_hostname not in groups.oo_masters_to_config

- name: Set ntp on nodes
  include_tasks: ntp.yml

- name: Configure all openshift nodes
  include_tasks: node_config.yaml

- name: Set bind mounts for containerized install
  include_tasks: bind_mounts.yaml
  when: openshift_is_containerized | bool
